### ISSUE TITLE
Change events enumeration logic

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-events#15]
Now we suppose we may have max 10k events per shard;
sweatcoin produced 2700 events in this block: https://explorer.near.org/blocks/DjMc3wUuNazky2VHRB8stTSpV7hReENqYjK7GJhFhQ1N.
It's only one contract, and I feel scared we can potentially overflow.
My suggestion: we should have 100k or even 1M events as the upper bound just to be sure we do not reach the overflow with our enumeration.

@frol what do you think?

**Comment by frol** [comment]
@telezhnaya Sounds good to me. As far as I remember, we have plenty of digits at our disposal, right? If so, sure, go ahead with whatever you know will work the best.

**Comment by telezhnaya** [comment]
Yeah, we have some digits for such cases :)

**Comment by telezhnaya** [comment]
We also can't cut timestamp to millis because of https://github.com/near/near-explorer/issues/1110
Just found this issue https://github.com/near/near-indexer-balances/issues/7

**Comment by telezhnaya** [comment]
Fixed by https://github.com/near/near-indexer-events/commit/ddbc7a2a1a01aa01abcf211988a797e5ee69cfe1
